symbols = ".*"

[accounts]

  [accounts.A1]
  master = true
  login = "tNShm3cu+MS4Hx2D+Q3U4CiqDFxu0kEoOK36BiAmU73AjfN/dYy+MZax"
  secret = "1W5Zar/uyMoOilIDVki6Lzl/eGfRCvaN8vXbNmiDOitwXfrtoAdhxDcQqt0KQjpsEVGfW07IoSSmHb0RguYmKA=="
  symbols = ".*"

[users]

  [users.test]
  password = "1234"
  symbols = ".*"

  [users.trader]
  password = "secret"
  accounts = [ "A1" ]
  symbols = "XBT/USD"
  monitor_period_secs = 60
  ban_period_secs = 300
  request_limit = 10
