symbols = [".*"]

[accounts]

  [accounts.A1]
  master = true
  login = "tNShm3cu+MS4Hx2D+Q3U4CiqDFxu0kEoOK36BiAmU73AjfN/dYy+MZax"
  secret = "1W5Zar/uyMoOilIDVki6Lzl/eGfRCvaN8vXbNmiDOitwXfrtoAdhxDcQqt0KQjpsEVGfW07IoSSmHb0RguYmKA=="
  symbols = [".*"]

[users]

  [users.test]
  password = "1234"
  symbols = ".*"

  [users.trader]
  password = "secret"
  accounts = [ "A1" ]
  symbols = "XBT/USD"

[rate_limits]

  [rate_limits.global]
    type = "ORDER_ACTION"
    aggregate = true
    request_limit = 100
    monitor_period = "10s"
    ban_period = "5min"

  [rate_limits.A1]
    type = "CREATE_ORDER"
    account = "A.*"
    request_limit = 30
    monitor_period = "1s"
    ban_period = "5min"

  [rate_limits.market_maker]
    type = "CREATE_ORDER"
    user = [ "trader" ]
    request_limit = 20
    monitor_period = "200ms"
    ban_period = "5min"
